# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /e/mozdev/home/.mozconfig-15 instead.

# PATH=/local/bin:/e/mozilla-build/wget:/e/mozilla-build/7zip:/e/mozilla-build/blat261/full:/e/mozilla-build/python:/e/mozilla-build/svn-win32-1.6.3/bin:/e/mozilla-build/upx203w:/e/mozilla-build/emacs-22.3/bin:/e/mozilla-build/info-zip:/e/mozilla-build/nsis-2.22:/e/mozilla-build/nsis-2.33u:/e/mozilla-build/nsis-2.46u:/e/mozilla-build/wix-351728:/e/mozilla-build/hg:/e/mozilla-build/python/Scripts:/e/mozilla-build/kdiff3:/e/mozilla-build/yasm:.:/usr/local/bin:/mingw/bin:/bin:/c/Program Files (x86)/Microsoft F#/v4.0/:/d/VS2010/VSTSDB/Deploy:/d/VS2010/Common7/IDE/:/d/VS2010/VC/BIN:/d/VS2010/Common7/Tools:/c/Windows/Microsoft.NET/Framework/v4.0.30319:/c/Windows/Microsoft.NET/Framework/v3.5:/d/VS2010/VC/VCPackages:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/HTML Help Workshop:/d/VS2010/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin/NETFX 4.0 Tools:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/e/mozilla-build/moztools/bin:/e/mozilla-build/vim/vim72
MOZ_OBJDIR=$(TOPSRCDIR)/build-optimized-vc10
MOZ_MAKE_FLAGS=-j1
MOZ_APP_NAME=palemoon
MOZ_APP_DISPLAYNAME=Palemoon
# --with-distribution-id=Palemoon is used by configure (not client.mk)
# --enable-update-packaging is used by configure (not client.mk)
# --enable-official-branding is used by configure (not client.mk)
MOZ_CO_PROJECT=browser
# --enable-application=browser is used by configure (not client.mk)
# --enable-optimize=-O2 -arch:SSE2 -GFLs -GS- -fp:precise -Qfast_transcendentals is used by configure (not client.mk)
# --enable-jemalloc is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --enable-chrome-format=jar is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-mochitests is used by configure (not client.mk)
# --enable-strip is used by configure (not client.mk)
# --disable-crashreporter is used by configure (not client.mk)
# --disable-accessibility is used by configure (not client.mk)
# --disable-parental-controls is used by configure (not client.mk)
# --disable-maintenance-service is used by configure (not client.mk)
# --disable-windows-mobile-components is used by configure (not client.mk)
# --disable-metro is used by configure (not client.mk)
# --disable-activex is used by configure (not client.mk)
# --disable-activex-scripting is used by configure (not client.mk)
# --disable-logging is used by configure (not client.mk)
# --disable-necko-wifi is used by configure (not client.mk)
PROFILE_GEN_SCRIPT=sh $(HOME)/run-pm4.sh
export FOUND_MOZCONFIG := /e/mozdev/home/.mozconfig-15
